nyc_mobility:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '/Users/brandoncgay/Documents/Projects/nyc-mobility-weather-analytics/data/nyc_mobility.duckdb') }}"
      schema: core
      threads: 4
      extensions:
        - parquet
      settings:
        memory_limit: '8GB'

    prod:
      type: duckdb
      path: "md:nyc_mobility?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: core
      threads: 4
      extensions:
        - parquet
